<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithColumnFormatting;

use App\Models\SiteMasterFile;
use Carbon\Carbon;

use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Style\NumberFormat;
use PhpOffice\PhpSpreadsheet\Shared\Date;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;

class ExportSiteMasterfile implements FromCollection,WithHeadings
{
    /**
    * @return \Illuminate\Support\Collection
    */ 
    public function headings():array{
        return[
            'service_id',
            'circuit_id',
            'project_id',
            'date_new',
            'project_status',
            'order_ref_number',
            'order_date',
            'expected_delivery_date',
            'province',
            'metro_area',
            'client_name',
            'service_type',
            'client_ring',
            'client_code',
            'rate_mbit_s',
            'site_a',
            'site_b',
            'date_po_order_rx',
            'po_mrc',
            'po_nrc',
            'service_manager',
            'client_quotation_ref',
            'account_manager_name',
            'physical_address_site_a',
            'gps_co_ordinates_site_a_x',
            'gps_co_ordinates_site_a_y',
            'contact_name_site_a',
            'work_number_site_a',
            'mobile_number_site_a',
            'email_address_site_a',
            'physical_address_site_b',
            'gps_co_ordinates_site_b_x',
            'gps_co_ordinates_site_b_y',
            'contact_name_site_b',
            'work_number_site_b',
            'mobile_number_site_b',
            'email_address_site_b',
            'description',
            'lease_term_in_months',
            'crossconnect',
            'technical_hands',
            'core_network_colocation_facilities',
            'rack_space_18u',
            'rack_space_9u_core_access_active',
            'rack_space_9u_core_access_passive',
            'rack_space_1u_passive',
            'order_quantity_primary_link_pair_2_strand',
            'inclusive_of_a_redundant_link_1_pair',
            'sla',
            'sla_premium',
            'sla_type',
            'monthly_lease_charges',
            'non_recurring',
            'monthly_lease_charges_2',
            'landlord_name_site_b',
            'managing_agent_site_b',
            'landlord_name_site_a',
            'landlord_contact_number_a',
            'managing_agent_site_a',
            'landlord_contact_number_b',
            'la_invoice',
            'strands',
            'type',
            'service_delivery_status',
            'llc_received',
            'client_po_num',
            'vodacom_vcw',
            'service_delivery_comments',
            'kam_name',
            'order_type',
            'shc_status',
            'sch_date',
            'dc_to_dc',
            'feasibility_ref_nr',
            'network_types',
            'sales_comments',
            'special_build_nrc',
            'return_to_sales',
            'estimated_enterprise_usage',
            'termination_date',
            'port_type',
            'port_location',
            'port_number',
            'penalty_charges',
            'cancellation_date',
            'thrd_party_nrc',
            'thrd_party_mrc',
            'thrd_party_provider',
            'transmission_project',
            'request_type',
            'po_number',
            'planned_build_date',
            'data_reg_db',
            'region'
        ];
    }

    /**
    * @return \Illuminate\Support\Collection
    */
    public function collection()
    {
        $records = SiteMasterFile::get();

        $all_records = [];
        foreach ($records as $key => $value) {
            $all_records[] = [
                'service_id' => $value->service_id,
                'circuit_id' => $value->circuit_id,
                'project_id' => $value->project_id,
                'date_new' => $value->date_new,
                'project_status' => $value->project_status,
                'order_ref_number' => $value->order_ref_number,
                'order_date' => $value->order_date,
                'expected_delivery_date' => $value->expected_delivery_date,
                'province' => $value->province,
                'metro_area' => $value->metro_area,
                'client_name' => $value->client_name,
                'service_type' => $value->service_type,
                'client_ring' => $value->client_ring,
                'client_code' => $value->client_code,
                'rate_mbit_s' => $value->rate_mbit_s,
                'site_a' => $value->site_a,
                'site_b' => $value->site_b,
                'date_po_order_rx' => $value->date_po_order_rx,
                'po_mrc' => $value->po_mrc,
                'po_nrc' => $value->po_nrc,
                'service_manager' => $value->service_manager,
                'client_quotation_ref' => $value->client_quotation_ref,
                'account_manager_name' => $value->account_manager_name,
                'physical_address_site_a' => $value->physical_address_site_a,
                'gps_co_ordinates_site_a_x' => $value->gps_co_ordinates_site_a_x,
                'gps_co_ordinates_site_a_y' => $value->gps_co_ordinates_site_a_y,
                'contact_name_site_a' => $value->contact_name_site_a,
                'work_number_site_a' => $value->work_number_site_a,
                'mobile_number_site_a' => $value->mobile_number_site_a,
                'email_address_site_a' => $value->email_address_site_a,
                'physical_address_site_b' => $value->physical_address_site_b,
                'gps_co_ordinates_site_b_x' => $value->gps_co_ordinates_site_b_x,
                'gps_co_ordinates_site_b_y' => $value->gps_co_ordinates_site_b_y,
                'contact_name_site_b' => $value->contact_name_site_b,
                'work_number_site_b' => $value->work_number_site_b,
                'mobile_number_site_b' => $value->mobile_number_site_b,
                'email_address_site_b' => $value->email_address_site_b,
                'description' => $value->description,
                'lease_term_in_months' => $value->lease_term_in_months,
                'crossconnect' => $value->crossconnect,
                'technical_hands' => $value->technical_hands,
                'core_network_colocation_faciities'  => $value->core_network_colocation_faciities,
                'rack_space_18u'  => $value->rack_space_18u,
                'rack_space_9u_core_access_active'  => $value->rack_space_9u_core_access_active,
                'rack_space_9u_core_access_passive' => $value->rack_space_9u_core_access_passive,
                'rack_space_1u_passive'  => $value->rack_space_1u_passive,
                'order_quantity_primary_link_pair_2_strand'  => $value->order_quantity_primary_link_pair_2_strand,
                'inclusive_of_a_redundant_link_1_pair'  => $value->inclusive_of_a_redundant_link_1_pair,
                'sla'  => $value->sla,
                'sla_premium'  => $value->sla_premium,
                'sla_type'  => $value->sla_type,
                'monthly_lease_charges'  => $value->monthly_lease_charges,
                'non_recurring'  => $value->non_recurring,
                'monthly_lease_charges_2'  => $value->monthly_lease_charges_2,
                'landlord_name_site_b'  => $value->landlord_name_site_b,
                'managing_agent_site_b'  => $value->managing_agent_site_b,
                'landlord_name_site_a'  => $value->landlord_name_site_a,
                'landlord_contact_number_a'  => $value->landlord_contact_number_a,
                'managing_agent_site_a'  => $value->managing_agent_site_a,
                'landlord_contact_number_b'  => $value->landlord_contact_number_b,
                'la_invoice'  => $value->la_invoice,
                'strands'  => $value->strands,
                'type'  => $value->type,
                'service_delivery_status'  => $value->service_delivery_status,
                'llc_received'  => $value->llc_received,
                'client_po_num'  => $value->client_po_num,
                'vodacom_vcw'  => $value->vodacom_vcw,
                'service_delivery_comments'  => $value->service_delivery_comments,
                'kam_name'  => $value->kam_name,
                'order_type'  => $value->order_type,
                'shc_status'  => $value->shc_status,
                'sch_date'  => $value->sch_date,
                'dc_to_dc' => $value->dc_to_dc,
                'feasibility_ref_nr'  => $value->feasibility_ref_nr,
                'network_types' => $value->network_types,
                'sales_comments' => $value->sales_comments,
                'special_build_nrc' => $value->special_build_nrc,
                'return_to_sales' => $value->return_to_sales,
                'estimated_enterprise_usage'  => $value->estimated_enterprise_usage,
                'termination_date'  => $value->termination_date,
                'port_type'  => $value->port_type,
                'port_location'  => $value->port_location,
                'port_number'  => $value->port_number,
                'penalty_charges'  => $value->penalty_charges,
                'cancellation_date'  => $value->cancellation_date,
                'thrd_party_nrc'  => $value->thrd_party_nrc,
                'thrd_party_mrc'  => $value->thrd_party_mrc,
                'thrd_party_provider'  => $value->thrd_party_provider,
                'transmission_project'  => $value->transmission_project,
                'request_type'  => $value->request_type,
                'po_number'  => $value->po_number,
                'planned_build_date'  => $value->planned_build_date,
                'data_reg_db'  => $value->data_reg_db,
                'region'  => $value->region
            ];
        }

        return collect($all_records);
    }
}
